name: package Android
on:
  push:
    #branches:
    #  - master
    tags:
      - "v*"

jobs:
    builds:
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        # 拉取仓库代码
        - uses: actions/checkout@v3
          # 设置Java运行环境，可以设置为: 1.8
        - uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 17

          # 设置gradle环境(比如: 6.5)、打包命令
        - uses: gradle/gradle-build-action@v2
          with:
            gradle-version: current
            #arguments: bundleRelease
            arguments: assembleRelease

        # 设置gradle环境(比如: 6.5)、打包命令
        - uses: gradle/gradle-build-action@v2
          with:
            gradle-version: current
            arguments: bundleRelease

        # 签名apk
        - uses: r0adkll/sign-android-release@v1
          name: Sign app APK google
          id: sign_app_google
          with:
            releaseDirectory: app/build/outputs/apk/google/release
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_PASSWORD }}
          # 还能设置build-tools version，29.0.3好像不支持了
          env:
            # override default build-tools version (29.0.3) -- optional
            BUILD_TOOLS_VERSION: "35.0.0"

        # 签名apk
        - uses: r0adkll/sign-android-release@v1
          name: Sign app APK main
          id: sign_app_main
          with:
            releaseDirectory: app/build/outputs/apk/mainStore/release
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_PASSWORD }}
          # 还能设置build-tools version，29.0.3好像不支持了
          env:
            # override default build-tools version (29.0.3) -- optional
            BUILD_TOOLS_VERSION: "35.0.0"

        # 签名 bundle
        - uses: r0adkll/sign-android-release@v1
          name: Sign app google bundle
          id: sign_app_google_bundle
          with:
            releaseDirectory: app/build/outputs/bundle/googleRelease
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_PASSWORD }}
          # 还能设置build-tools version，29.0.3好像不支持了
          env:
            # override default build-tools version (29.0.3) -- optional
            BUILD_TOOLS_VERSION: "35.0.0"

        # 签名 bundle
        - uses: r0adkll/sign-android-release@v1
          name: Sign app main bundle
          id: sign_app_main_bundle
          with:
            releaseDirectory: app/build/outputs/bundle/mainStoreRelease
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_PASSWORD }}
          # 还能设置build-tools version，29.0.3好像不支持了
          env:
            # override default build-tools version (29.0.3) -- optional
            BUILD_TOOLS_VERSION: "35.0.0"

        #- run: mv ${{steps.sign_app.outputs.signedReleaseFile}} LittleGooseOffice_$GITHUB_REF_NAME.apk
        - run: mv ${{steps.sign_app_google.outputs.signedReleaseFile}} .
        - run: mv ${{steps.sign_app_main.outputs.signedReleaseFile}} .

        - run: mv ${{steps.sign_app_google_bundle.outputs.signedReleaseFile}} .
        - run: mv ${{steps.sign_app_main_bundle.outputs.signedReleaseFile}} .

        - uses: ncipollo/release-action@v1
          with:
            artifacts: "*.apk, *.aab"
            token: ${{ github.token }}
            generateReleaseNotes: true



